name: pchat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.0+3 # SQLite 数据库插件
  shared_preferences: ^2.5.3 # 用于本地存储
  sqflite_common_ffi: ^2.0.0 # FFI 版本的 sqflite
  hive: ^2.2.3 # NoSQL 数据库插件
  hive_flutter: ^1.1.0 # Hive 的 Flutter 插件
  path_provider: ^2.0.12 # 用于获取文件路径
  file_picker: ^5.3.2 # 文件选择器插件
  provider: ^6.1.5 # 状态管理插件

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/user_card_background.png
